TwitchEmotes_defaultpack = {
	-- lizzie_twitch
	[":33"] = "Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_twitch\\lizziev33.tga:28:28",
	[":333"] = "Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_twitch\\lizziev333.tga:28:28",
	["AAAA"] = "Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_twitch\\lizzievaaaa.tga:28:28",
	["AHHH"] = "Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_twitch\\lizzievahhh.tga:28:28",
	["Angy"] = "Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_twitch\\lizzievcatangy.tga:28:28",
	["bestaSmile"] = "Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_twitch\\lizzievbestasmile.tga:28:28",
	["clappi"] = "Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_twitch\\lizzievclappi.tga:28:28",
	["gigl"] = "Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_twitch\\lizzievgigl.tga:28:28",
	["ICANT"] = "Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_twitch\\lizzievicant.tga:28:28",
	["KEKW"] = "Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_twitch\\lizzievkekw.tga:28:28",
	["kok"] = "Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_twitch\\lizzievkok.tga:28:28",
	["lizzievANGY"] = "Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_twitch\\lizzievangy.tga:28:28",
	["lizzievARRIVE"] = "Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_twitch\\lizzievarrive.tga:28:28",
	["lizzievBLANKIES"] = "Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_twitch\\lizzievblankies.tga:28:28",
	["lizzievBLUSH"] = "Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_twitch\\lizzievblush.tga:28:28",
	["lizzievBONGO"] = "Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_twitch\\lizzievbongo.tga:28:28",
	["lizzievBONK"] = "Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_twitch\\lizzievbonk.tga:28:28",
	["lizzievBUBBLEGUM"] = "Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_twitch\\lizzievbubblegum.tga:28:28",
	["CAUGHT"] = "Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_twitch\\lizzievcaught.tga:28:28",
	["lizzievCHEER"] = "Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_twitch\\lizzievcheer.tga:28:28",
	["lizzievCHEERS"] = "Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_twitch\\lizzievcheers.tga:28:28",
	["lizzievCHUG"] = "Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_twitch\\lizzievchug.tga:28:28",
	["lizzievCLAP"] = "Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_twitch\\lizzievclap.tga:28:28",
	["lizzievCLEAN"] = "Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_twitch\\lizzievclean.tga:28:28",
	["lizzievCOFFEE"] = "Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_twitch\\lizzievcoffee.tga:28:28",
	["lizzievCOPIUM"] = "Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_twitch\\lizzievcopium.tga:28:28",
	["lizzievCOZY"] = "Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_twitch\\lizzievcozy.tga:28:28",
	["lizzievCULT"] = "Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_twitch\\lizzievcult.tga:28:28",
	["lizzievDANCE"] = "Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_twitch\\lizzievdance.tga:28:28",
	["lizzievDETECTIVE"] = "Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_twitch\\lizzievdetective.tga:28:28",
	["lizzievDINKDONK"] = "Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_twitch\\lizzievdinkdonk.tga:28:28",
	["ERM"] = "Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_twitch\\lizzieverm.tga:28:28",
	["lizzievFIGHT"] = "Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_twitch\\lizzievfight.tga:28:28",
	["lizzievFINE"] = "Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_twitch\\lizzievfine.tga:28:28",
	["lizzievFLEX"] = "Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_twitch\\lizzievflex.tga:28:28",
	["lizzievFLOWER"] = "Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_twitch\\lizzievflower.tga:28:28",
	["lizzievFY"] = "Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_twitch\\lizzievfy.tga:28:28",
	["lizzievGIGGLE"] = "Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_twitch\\lizzievgiggle.tga:28:28",
	["lizzievGN"] = "Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_twitch\\lizzievgn.tga:28:28",
	["lizzievGUN"] = "Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_twitch\\lizzievgun.tga:28:28",
	["lizzievHEADBANG"] = "Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_twitch\\lizzievheadbang.tga:28:28",
	["lizzievHEARTEYES"] = "Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_twitch\\lizzievhearteyes.tga:28:28",
	["lizzievHI"] = "Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_twitch\\lizzievhi.tga:28:28",
	["lizzievHIDE"] = "Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_twitch\\lizzievhide.tga:28:28",
	["lizzievHOWDY"] = "Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_twitch\\lizzievhowdy.tga:28:28",
	["lizzievHUG"] = "Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_twitch\\lizzievhug.tga:28:28",
	["lizzievKISS"] = "Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_twitch\\lizzievkiss.tga:28:28",
	["lizzievL"] = "Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_twitch\\lizzievl.tga:28:28",
	["lizzievLATE"] = "Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_twitch\\lizzievlate.tga:28:28",
	["lizzievLEGS"] = "Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_twitch\\lizzievlegs.tga:28:28",
	["lizzievLICK"] = "Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_twitch\\lizzievlick.tga:28:28",
	["lizzievLOVE"] = "Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_twitch\\lizzievlove.tga:28:28",
	["NODDERS"] = "Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_twitch\\lizzievnodders.tga:28:28",
	["NOPERS"] = "Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_twitch\\lizzievnopers.tga:28:28",
	["lizzievNOU"] = "Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_twitch\\lizzievnou.tga:28:28",
	["lizzievPAT"] = "Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_twitch\\lizzievpat.tga:28:28",
	["PaueHog"] = "Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_twitch\\lizzievpausehog.tga:28:28",
	["Pog"] = "Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_twitch\\lizzievpog.tga:28:28",
	["lizzievROCK"] = "Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_twitch\\lizzievrock.tga:28:28",
	["lizzievSAD"] = "Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_twitch\\lizzievsad.tga:28:28",
	["lizzievSHY"] = "Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_twitch\\lizzievshy.tga:28:28",
	["lizzievSIP"] = "Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_twitch\\lizzievsip.tga:28:28",
	["lizzievSLAY"] = "Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_twitch\\lizzievslay.tga:28:28",
	["lizzievSMUSH"] = "Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_twitch\\lizzievsmush.tga:28:28",
	["lizzievSTAB"] = "Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_twitch\\lizzievstab.tga:28:28",
	["lizzievTOFFLA"] = "Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_twitch\\lizzievtoffla.tga:28:28",
	["lizzievUWU"] = "Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_twitch\\lizzievuwu.tga:28:28",
	["vibee"] = "Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_twitch\\lizzievvibee.tga:28:28",
	["lizzievWIGGLE"] = "Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_twitch\\lizzievwiggle.tga:28:28",
	["lizzievWOWGI"] = "Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_twitch\\lizzievwowgi.tga:28:28",
	["lizzievYESSIR"] = "Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_twitch\\lizzievyessir.tga:28:28",
	["Madge"] = "Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_twitch\\lizzievsadge.tga:28:28",
	["MONKA"] = "Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_twitch\\lizzievmonka.tga:28:28",
	["nolook"] = "Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_twitch\\lizzievnolook.tga:28:28",
	["oshit"] = "Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_twitch\\lizzievoshit.tga:28:28",
	["Sadge"] = "Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_twitch\\lizzievmadge.tga:28:28",
	["SLAYYY"] = "Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_twitch\\lizzievslayyy.tga:28:28",
	["SMH"] = "Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_twitch\\lizzievsmh.tga:28:28",
	["YAAAS"] = "Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_twitch\\lizzievyaaas.tga:28:28",
};

TwitchEmotes_animation_metadata = {
	["Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_twitch\\lizziev333.tga"] = {["nFrames"] = 95, ["frameWidth"] = 144, ["frameHeight"] = 128, ["imageWidth"] = 144, ["imageHeight"] = 12160, ["framerate"] = 25},
	["Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_twitch\\lizzievaaaa.tga"] = {["nFrames"] = 7, ["frameWidth"] = 128, ["frameHeight"] = 128, ["imageWidth"] = 128, ["imageHeight"] = 896, ["framerate"] = 25},
	["Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_twitch\\lizzievangy.tga"] = {["nFrames"] = 53, ["frameWidth"] = 56, ["frameHeight"] = 56, ["imageWidth"] = 56, ["imageHeight"] = 2968, ["framerate"] = 25},
	["Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_twitch\\lizzievarrive.tga"] = {["nFrames"] = 60, ["frameWidth"] = 56, ["frameHeight"] = 56, ["imageWidth"] = 56, ["imageHeight"] = 3360, ["framerate"] = 25},
	["Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_twitch\\lizzievblankies.tga"] = {["nFrames"] = 24, ["frameWidth"] = 56, ["frameHeight"] = 56, ["imageWidth"] = 56, ["imageHeight"] = 1344, ["framerate"] = 25},
	["Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_twitch\\lizzievbongo.tga"] = {["nFrames"] = 12, ["frameWidth"] = 56, ["frameHeight"] = 56, ["imageWidth"] = 56, ["imageHeight"] = 672, ["framerate"] = 25},
	["Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_twitch\\lizzievbubblegum.tga"] = {["nFrames"] = 60, ["frameWidth"] = 56, ["frameHeight"] = 56, ["imageWidth"] = 56, ["imageHeight"] = 3360, ["framerate"] = 25},
	["Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_twitch\\lizzievcatangy.tga"] = {["nFrames"] = 52, ["frameWidth"] = 128, ["frameHeight"] = 128, ["imageWidth"] = 128, ["imageHeight"] = 6656, ["framerate"] = 25},
	["Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_twitch\\lizzievcheer.tga"] = {["nFrames"] = 38, ["frameWidth"] = 56, ["frameHeight"] = 56, ["imageWidth"] = 56, ["imageHeight"] = 2128, ["framerate"] = 25},
	["Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_twitch\\lizzievcheers.tga"] = {["nFrames"] = 27, ["frameWidth"] = 56, ["frameHeight"] = 56, ["imageWidth"] = 56, ["imageHeight"] = 1512, ["framerate"] = 25},
	["Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_twitch\\lizzievchug.tga"] = {["nFrames"] = 16, ["frameWidth"] = 56, ["frameHeight"] = 56, ["imageWidth"] = 56, ["imageHeight"] = 896, ["framerate"] = 25},
	["Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_twitch\\lizzievclap.tga"] = {["nFrames"] = 10, ["frameWidth"] = 56, ["frameHeight"] = 56, ["imageWidth"] = 56, ["imageHeight"] = 560, ["framerate"] = 25},
	["Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_twitch\\lizzievclappi.tga"] = {["nFrames"] = 29, ["frameWidth"] = 224, ["frameHeight"] = 128, ["imageWidth"] = 224, ["imageHeight"] = 3712, ["framerate"] = 25},
	["Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_twitch\\lizzievclean.tga"] = {["nFrames"] = 24, ["frameWidth"] = 56, ["frameHeight"] = 56, ["imageWidth"] = 56, ["imageHeight"] = 1344, ["framerate"] = 25},
	["Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_twitch\\lizzievcoffee.tga"] = {["nFrames"] = 40, ["frameWidth"] = 56, ["frameHeight"] = 56, ["imageWidth"] = 56, ["imageHeight"] = 2240, ["framerate"] = 25},
	["Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_twitch\\lizzievdinkdonk.tga"] = {["nFrames"] = 8, ["frameWidth"] = 56, ["frameHeight"] = 56, ["imageWidth"] = 56, ["imageHeight"] = 448, ["framerate"] = 25},
	["Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_twitch\\lizzievflower.tga"] = {["nFrames"] = 41, ["frameWidth"] = 56, ["frameHeight"] = 56, ["imageWidth"] = 56, ["imageHeight"] = 2296, ["framerate"] = 25},
	["Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_twitch\\lizzievgigl.tga"] = {["nFrames"] = 10, ["frameWidth"] = 140, ["frameHeight"] = 128, ["imageWidth"] = 140, ["imageHeight"] = 1280, ["framerate"] = 25},
	["Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_twitch\\lizzievheadbang.tga"] = {["nFrames"] = 6, ["frameWidth"] = 56, ["frameHeight"] = 56, ["imageWidth"] = 56, ["imageHeight"] = 336, ["framerate"] = 12},
	["Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_twitch\\lizzievhi.tga"] = {["nFrames"] = 24, ["frameWidth"] = 56, ["frameHeight"] = 56, ["imageWidth"] = 56, ["imageHeight"] = 1344, ["framerate"] = 25},
	["Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_twitch\\lizzievhide.tga"] = {["nFrames"] = 28, ["frameWidth"] = 56, ["frameHeight"] = 56, ["imageWidth"] = 56, ["imageHeight"] = 1568, ["framerate"] = 12},
	["Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_twitch\\lizzievhowdy.tga"] = {["nFrames"] = 29, ["frameWidth"] = 56, ["frameHeight"] = 56, ["imageWidth"] = 56, ["imageHeight"] = 1624, ["framerate"] = 25},
	["Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_twitch\\lizzievkiss.tga"] = {["nFrames"] = 27, ["frameWidth"] = 56, ["frameHeight"] = 56, ["imageWidth"] = 56, ["imageHeight"] = 1512, ["framerate"] = 25},
	["Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_twitch\\lizzievkok.tga"] = {["nFrames"] = 70, ["frameWidth"] = 132, ["frameHeight"] = 128, ["imageWidth"] = 132, ["imageHeight"] = 8960, ["framerate"] = 25},
	["Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_twitch\\lizzievl.tga"] = {["nFrames"] = 48, ["frameWidth"] = 56, ["frameHeight"] = 56, ["imageWidth"] = 56, ["imageHeight"] = 2688, ["framerate"] = 25},
	["Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_twitch\\lizzievlegs.tga"] = {["nFrames"] = 24, ["frameWidth"] = 56, ["frameHeight"] = 56, ["imageWidth"] = 56, ["imageHeight"] = 1344, ["framerate"] = 25},
	["Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_twitch\\lizzievlick.tga"] = {["nFrames"] = 38, ["frameWidth"] = 56, ["frameHeight"] = 56, ["imageWidth"] = 56, ["imageHeight"] = 2128, ["framerate"] = 25},
	["Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_twitch\\lizzievnou.tga"] = {["nFrames"] = 10, ["frameWidth"] = 56, ["frameHeight"] = 56, ["imageWidth"] = 56, ["imageHeight"] = 560, ["framerate"] = 12},
	["Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_twitch\\lizzievsmh.tga"] = {["nFrames"] = 9, ["frameWidth"] = 152, ["frameHeight"] = 128, ["imageWidth"] = 152, ["imageHeight"] = 1152, ["framerate"] = 12},
	["Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_twitch\\lizzievsmush.tga"] = {["nFrames"] = 44, ["frameWidth"] = 56, ["frameHeight"] = 56, ["imageWidth"] = 56, ["imageHeight"] = 2464, ["framerate"] = 25},
	["Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_twitch\\lizzievuwu.tga"] = {["nFrames"] = 30, ["frameWidth"] = 56, ["frameHeight"] = 56, ["imageWidth"] = 56, ["imageHeight"] = 1680, ["framerate"] = 25},
	["Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_twitch\\lizzievwiggle.tga"] = {["nFrames"] = 48, ["frameWidth"] = 56, ["frameHeight"] = 56, ["imageWidth"] = 56, ["imageHeight"] = 2688, ["framerate"] = 25},
	["Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_twitch\\lizzievdance.tga"] = {["nFrames"] = 24, ["frameWidth"] = 112, ["frameHeight"] = 112, ["imageWidth"] = 112, ["imageHeight"] = 2688, ["framerate"] = 25},
	["Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_twitch\\lizzieverm.tga"] = {["nFrames"] = 51, ["frameWidth"] = 128, ["frameHeight"] = 128, ["imageWidth"] = 128, ["imageHeight"] = 6528, ["framerate"] = 25},
	["Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_twitch\\lizzievnodders.tga"] = {["nFrames"] = 4, ["frameWidth"] = 128, ["frameHeight"] = 128, ["imageWidth"] = 128, ["imageHeight"] = 512, ["framerate"] = 25},
	["Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_twitch\\lizzievnopers.tga"] = {["nFrames"] = 4, ["frameWidth"] = 128, ["frameHeight"] = 128, ["imageWidth"] = 128, ["imageHeight"] = 512, ["framerate"] = 25},
	["Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_twitch\\lizzievrock.tga"] = {["nFrames"] = 24, ["frameWidth"] = 112, ["frameHeight"] = 112, ["imageWidth"] = 112, ["imageHeight"] = 2688, ["framerate"] = 25},
	["Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_twitch\\lizzievvibee.tga"] = {["nFrames"] = 90, ["frameWidth"] = 152, ["frameHeight"] = 128, ["imageWidth"] = 152, ["imageHeight"] = 11520, ["framerate"] = 25},
}

TwitchEmotes_emoticons = {
	-- lizzie_twitch
	[":33"] = ":33",
	[":333"] = ":333",
	["AAAA"] = "AAAA",
	["AHHH"] = "AHHH",
	["Angy"] = "Angy",
	["bestaSmile"] = "bestaSmile",
	["clappi"] = "clappi",
	["gigl"] = "gigl",
	["ICANT"] = "ICANT",
	["KEKW"] = "KEKW",
	["kok"] = "kok",
	["lizzievANGY"] = "lizzievANGY",
	["lizzievARRIVE"] = "lizzievARRIVE",
	["lizzievBLANKIES"] = "lizzievBLANKIES",
	["lizzievBLUSH"] = "lizzievBLUSH",
	["lizzievBONGO"] = "lizzievBONGO",
	["lizzievBONK"] = "lizzievBONK",
	["lizzievBUBBLEGUM"] = "lizzievBUBBLEGUM",
	["CAUGHT"] = "CAUGHT",
	["lizzievCHEER"] = "lizzievCHEER",
	["lizzievCHEERS"] = "lizzievCHEERS",
	["lizzievCHUG"] = "lizzievCHUG",
	["lizzievCLAP"] = "lizzievCLAP",
	["lizzievCLEAN"] = "lizzievCLEAN",
	["lizzievCOFFEE"] = "lizzievCOFFEE",
	["lizzievCOPIUM"] = "lizzievCOPIUM",
	["lizzievCOZY"] = "lizzievCOZY",
	["lizzievCULT"] = "lizzievCULT",
	["lizzievDANCE"] = "lizzievDANCE",
	["lizzievDETECTIVE"] = "lizzievDETECTIVE",
	["lizzievDINKDONK"] = "lizzievDINKDONK",
	["ERM"] = "lizzievERM",
	["lizzievFIGHT"] = "lizzievFIGHT",
	["lizzievFINE"] = "lizzievFINE",
	["lizzievFLEX"] = "lizzievFLEX",
	["lizzievFLOWER"] = "lizzievFLOWER",
	["lizzievFY"] = "lizzievFY",
	["lizzievGIGGLE"] = "lizzievGIGGLE",
	["lizzievGN"] = "lizzievGN",
	["lizzievGUN"] = "lizzievGUN",
	["lizzievHEADBANG"] = "lizzievHEADBANG",
	["lizzievHEARTEYES"] = "lizzievHEARTEYES",
	["lizzievHI"] = "lizzievHI",
	["lizzievHIDE"] = "lizzievHIDE",
	["lizzievHOWDY"] = "lizzievHOWDY",
	["lizzievHUG"] = "lizzievHUG",
	["lizzievKISS"] = "lizzievKISS",
	["lizzievL"] = "lizzievL",
	["lizzievLATE"] = "lizzievLATE",
	["lizzievLEGS"] = "lizzievLEGS",
	["lizzievLICK"] = "lizzievLICK",
	["lizzievLOVE"] = "lizzievLOVE",
	["NODDERS"] = "lizzievNODDERS",
	["NOPERS"] = "lizzievNOPERS",
	["lizzievNOU"] = "lizzievNOU",
	["lizzievPAT"] = "lizzievPAT",
	["PauseHog"] = "PauseHog",
	["Pog"] = "Pog",
	["lizzievROCK"] = "lizzievROCK",
	["lizzievSAD"] = "lizzievSAD",
	["lizzievSHY"] = "lizzievSHY",
	["lizzievSIP"] = "lizzievSIP",
	["lizzievSLAY"] = "lizzievSLAY",
	["lizzievSMUSH"] = "lizzievSMUSH",
	["lizzievSTAB"] = "lizzievSTAB",
	["lizzievTOFFLA"] = "lizzievTOFFLA",
	["lizzievUWU"] = "lizzievUWU",
	["vibee"] = "vibee",
	["lizzievWIGGLE"] = "lizzievWIGGLE",
	["lizzievWOWGI"] = "lizzievWOWGI",
	["lizzievYESSIR"] = "lizzievYESSIR",
	["Madge"] = "Madge",
	["MONKA"] = "MONKA",
	["nolook"] = "nolook",
	["oshit"] = "oshit",
	["Sadge"] = "Sadge",
	["SLAYYY"] = "SLAYYY",
	["SMH"] = "SMH",
	["YAAAS"] = "YAAAS",
};

TwitchEmotes_ExcludedSuggestions = {
	"Jons", ":jons:", ":twoofakind:", "HammersArk", "HammersNoArk", "Shelia", "LULWWW", ":mo:", ":penguin:", "Gerdlerk1", "Gerdlerk2", "Gerdlerk3", "Gerdlerk4", "Lucimage", "Bowtherapy", "NickyQW","gachiSLAPW","peepoMadW","FeelsBadManW","FeelsGoodManW","FeelsgoodManW","FeelsOkayManW","FeelsSleepyManW","PepeHandsW","PepeJAMW","WeirdWW","MooCowW","peepoLoveW","peepoPlotW","FeelsCryManW","monakW","LovepeepoW","WeirdJAMW","peepoExitW","FeelsLoveManW","HeartatoW","KEKWW","PogWartsW",":epicW:","Lyeasy","LyeREE","LyeCute","LyEZ","LyeShrug",":smook:","SmookDead","SmookEvil","SmookGasm","SmookMad","SmookNervous","SmookSad","SmookSpook","SmookWeird","SmookWink","SmookSmile", "unholysip", "BedgeMorgan", "MikeSmug"
}
