TwitchEmotes_defaultpack = {
	-- lizzie_vargfrost
	[":33"] = "Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_vargfrost\\lizziev33.tga:28:28",
	[":333"] = "Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_vargfrost\\lizziev333.tga:28:28",
	["AAAA"] = "Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_vargfrost\\lizzievaaaa.tga:28:28",
	["AHHH"] = "Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_vargfrost\\lizzievahhh.tga:28:28",
	["Angy"] = "Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_vargfrost\\lizzievcatangy.tga:28:28",
	["bestaSmile"] = "Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_vargfrost\\lizzievbestasmile.tga:28:28",
	["ICANT"] = "Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_vargfrost\\lizzievicant.tga:28:28",
	["KEKW"] = "Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_vargfrost\\lizzievkekw.tga:28:28",
	["kok"] = "Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_vargfrost\\lizzievkok.tga:28:28",
	["lizzievANGY"] = "Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_vargfrost\\lizzievangy.tga:28:28",
	["lizzievARRIVE"] = "Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_vargfrost\\lizzievarrive.tga:28:28",
	["lizzievBLANKIES"] = "Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_vargfrost\\lizzievblankies.tga:28:28",
	["lizzievBLUSH"] = "Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_vargfrost\\lizzievblush.tga:28:28",
	["lizzievBONGO"] = "Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_vargfrost\\lizzievbongo.tga:28:28",
	["lizzievBUBBLEGUM"] = "Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_vargfrost\\lizzievbubblegum.tga:28:28",
	["lizzievCHEER"] = "Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_vargfrost\\lizzievcheer.tga:28:28",
	["lizzievCHEERS"] = "Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_vargfrost\\lizzievcheers.tga:28:28",
	["lizzievCHUG"] = "Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_vargfrost\\lizzievchug.tga:28:28",
	["lizzievCLAP"] = "Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_vargfrost\\lizzievclap.tga:28:28",
	["clappi"] = "Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_vargfrost\\lizzievclappi.tga:28:28",
	["lizzievCLEAN"] = "Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_vargfrost\\lizzievclean.tga:28:28",
	["lizzievCOFFEE"] = "Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_vargfrost\\lizzievcoffee.tga:28:28",
	["lizzievCOPIUM"] = "Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_vargfrost\\lizzievcopium.tga:28:28",
	["lizzievCOZY"] = "Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_vargfrost\\lizzievcozy.tga:28:28",
	["lizzievCULT"] = "Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_vargfrost\\lizzievcult.tga:28:28",
	["lizzievDETECTIVE"] = "Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_vargfrost\\lizzievdetective.tga:28:28",
	["lizzievDINKDONK"] = "Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_vargfrost\\lizzievdinkdonk.tga:28:28",
	["lizzievFIGHT"] = "Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_vargfrost\\lizzievfight.tga:28:28",
	["lizzievFINE"] = "Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_vargfrost\\lizzievfine.tga:28:28",
	["lizzievFLEX"] = "Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_vargfrost\\lizzievflex.tga:28:28",
	["lizzievFLOWER"] = "Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_vargfrost\\lizzievflower.tga:28:28",
	["lizzievFY"] = "Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_vargfrost\\lizzievfy.tga:28:28",
	["lizzievGIGGLE"] = "Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_vargfrost\\lizzievgiggle.tga:28:28",
	["gigl"] = "Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_vargfrost\\lizzievgigl.tga:28:28",
	["lizzievGUN"] = "Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_vargfrost\\lizzievgun.tga:28:28",
	["lizzievHEADBANG"] = "Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_vargfrost\\lizzievheadbang.tga:28:28",
	["lizzievHEARTEYES"] = "Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_vargfrost\\lizzievhearteyes.tga:28:28",
	["lizzievHI"] = "Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_vargfrost\\lizzievhi.tga:28:28",
	["lizzievHIDE"] = "Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_vargfrost\\lizzievhide.tga:28:28",
	["lizzievHOWDY"] = "Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_vargfrost\\lizzievhowdy.tga:28:28",
	["lizzievHUG"] = "Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_vargfrost\\lizzievhug.tga:28:28",
	["lizzievKISS"] = "Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_vargfrost\\lizzievkiss.tga:28:28",
	["lizzievL"] = "Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_vargfrost\\lizzievl.tga:28:28",
	["lizzievLATE"] = "Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_vargfrost\\lizzievlate.tga:28:28",
	["lizzievLEGS"] = "Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_vargfrost\\lizzievlegs.tga:28:28",
	["lizzievLICK"] = "Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_vargfrost\\lizzievlick.tga:28:28",
	["lizzievLOVE"] = "Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_vargfrost\\lizzievlove.tga:28:28",
	["Madge"] = "Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_vargfrost\\lizzievmadge.tga:28:28",
	["MONKA"] = "Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_vargfrost\\lizzievmonka.tga:28:28",
	["lizzievNOU"] = "Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_vargfrost\\lizzievnou.tga:28:28",
	["lizzievSAD"] = "Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_vargfrost\\lizzievsad.tga:28:28",
	["Sadge"] = "Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_vargfrost\\lizzievsadge.tga:28:28",
	["lizzievSHY"] = "Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_vargfrost\\lizzievshy.tga:28:28",
	["lizzievSIP"] = "Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_vargfrost\\lizzievsip.tga:28:28",
	["lizzievSLAY"] = "Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_vargfrost\\lizzievslay.tga:28:28",
	["SMH"] = "Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_vargfrost\\lizzievsmh.tga:28:28",
	["lizzievSMUSH"] = "Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_vargfrost\\lizzievsmush.tga:28:28",
	["lizzievSTAB"] = "Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_vargfrost\\lizzievstab.tga:28:28",
	["lizzievTOFFLA"] = "Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_vargfrost\\lizzievtoffla.tga:28:28",
	["lizzievUWU"] = "Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_vargfrost\\lizzievuwu.tga:28:28",
	["lizzievWIGGLE"] = "Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_vargfrost\\lizzievwiggle.tga:28:28",
	["lizzievWOWGI"] = "Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_vargfrost\\lizzievwowgi.tga:28:28",
	["lizzievYESSIR"] = "Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_vargfrost\\lizzievyessir.tga:28:28",
	["nolook"] = "Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_vargfrost\\lizzievnolook.tga:28:28",
	["oshit"] = "Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_vargfrost\\lizzievoshit.tga:28:28",
	["SLAYYY"] = "Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_vargfrost\\lizzievslayyy.tga:28:28",
	["YAAAS"] = "Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_vargfrost\\lizzievyaaas.tga:28:28",
};

TwitchEmotes_animation_metadata = {
	["Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_vargfrost\\lizziev333.tga"] = {["nFrames"] = 95, ["frameWidth"] = 144, ["frameHeight"] = 128, ["imageWidth"] = 144, ["imageHeight"] = 12160, ["framerate"] = 25},
	["Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_vargfrost\\lizzievaaaa.tga"] = {["nFrames"] = 7, ["frameWidth"] = 128, ["frameHeight"] = 128, ["imageWidth"] = 128, ["imageHeight"] = 896, ["framerate"] = 25},
	["Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_vargfrost\\lizzievangy.tga"] = {["nFrames"] = 53, ["frameWidth"] = 56, ["frameHeight"] = 56, ["imageWidth"] = 56, ["imageHeight"] = 2968, ["framerate"] = 25},
	["Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_vargfrost\\lizzievarrive.tga"] = {["nFrames"] = 60, ["frameWidth"] = 56, ["frameHeight"] = 56, ["imageWidth"] = 56, ["imageHeight"] = 3360, ["framerate"] = 25},
	["Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_vargfrost\\lizzievblankies.tga"] = {["nFrames"] = 24, ["frameWidth"] = 56, ["frameHeight"] = 56, ["imageWidth"] = 56, ["imageHeight"] = 1344, ["framerate"] = 25},
	["Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_vargfrost\\lizzievbongo.tga"] = {["nFrames"] = 12, ["frameWidth"] = 56, ["frameHeight"] = 56, ["imageWidth"] = 56, ["imageHeight"] = 672, ["framerate"] = 25},
	["Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_vargfrost\\lizzievbubblegum.tga"] = {["nFrames"] = 60, ["frameWidth"] = 56, ["frameHeight"] = 56, ["imageWidth"] = 56, ["imageHeight"] = 3360, ["framerate"] = 25},
	["Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_vargfrost\\lizzievcatangy.tga"] = {["nFrames"] = 52, ["frameWidth"] = 128, ["frameHeight"] = 128, ["imageWidth"] = 128, ["imageHeight"] = 6656, ["framerate"] = 25},
	["Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_vargfrost\\lizzievcheer.tga"] = {["nFrames"] = 38, ["frameWidth"] = 56, ["frameHeight"] = 56, ["imageWidth"] = 56, ["imageHeight"] = 2128, ["framerate"] = 25},
	["Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_vargfrost\\lizzievcheers.tga"] = {["nFrames"] = 27, ["frameWidth"] = 56, ["frameHeight"] = 56, ["imageWidth"] = 56, ["imageHeight"] = 1512, ["framerate"] = 25},
	["Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_vargfrost\\lizzievchug.tga"] = {["nFrames"] = 16, ["frameWidth"] = 56, ["frameHeight"] = 56, ["imageWidth"] = 56, ["imageHeight"] = 896, ["framerate"] = 25},
	["Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_vargfrost\\lizzievclap.tga"] = {["nFrames"] = 10, ["frameWidth"] = 56, ["frameHeight"] = 56, ["imageWidth"] = 56, ["imageHeight"] = 560, ["framerate"] = 25},
	["Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_vargfrost\\lizzievclean.tga"] = {["nFrames"] = 24, ["frameWidth"] = 56, ["frameHeight"] = 56, ["imageWidth"] = 56, ["imageHeight"] = 1344, ["framerate"] = 25},
	["Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_vargfrost\\lizzievcoffee.tga"] = {["nFrames"] = 40, ["frameWidth"] = 56, ["frameHeight"] = 56, ["imageWidth"] = 56, ["imageHeight"] = 2240, ["framerate"] = 25},
	["Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_vargfrost\\lizzievdinkdonk.tga"] = {["nFrames"] = 8, ["frameWidth"] = 56, ["frameHeight"] = 56, ["imageWidth"] = 56, ["imageHeight"] = 448, ["framerate"] = 25},
	["Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_vargfrost\\lizzievflower.tga"] = {["nFrames"] = 41, ["frameWidth"] = 56, ["frameHeight"] = 56, ["imageWidth"] = 56, ["imageHeight"] = 2296, ["framerate"] = 25},
	["Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_vargfrost\\lizzievheadbang.tga"] = {["nFrames"] = 6, ["frameWidth"] = 56, ["frameHeight"] = 56, ["imageWidth"] = 56, ["imageHeight"] = 336, ["framerate"] = 12},
	["Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_vargfrost\\lizzievhi.tga"] = {["nFrames"] = 24, ["frameWidth"] = 56, ["frameHeight"] = 56, ["imageWidth"] = 56, ["imageHeight"] = 1344, ["framerate"] = 25},
	["Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_vargfrost\\lizzievhide.tga"] = {["nFrames"] = 28, ["frameWidth"] = 56, ["frameHeight"] = 56, ["imageWidth"] = 56, ["imageHeight"] = 1568, ["framerate"] = 12},
	["Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_vargfrost\\lizzievhowdy.tga"] = {["nFrames"] = 29, ["frameWidth"] = 56, ["frameHeight"] = 56, ["imageWidth"] = 56, ["imageHeight"] = 1624, ["framerate"] = 25},
	["Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_vargfrost\\lizzievkiss.tga"] = {["nFrames"] = 27, ["frameWidth"] = 56, ["frameHeight"] = 56, ["imageWidth"] = 56, ["imageHeight"] = 1512, ["framerate"] = 25},
	["Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_vargfrost\\lizzievkok.tga"] = {["nFrames"] = 70, ["frameWidth"] = 132, ["frameHeight"] = 128, ["imageWidth"] = 132, ["imageHeight"] = 8960, ["framerate"] = 25},
	["Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_vargfrost\\lizzievl.tga"] = {["nFrames"] = 48, ["frameWidth"] = 56, ["frameHeight"] = 56, ["imageWidth"] = 56, ["imageHeight"] = 2688, ["framerate"] = 25},
	["Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_vargfrost\\lizzievlegs.tga"] = {["nFrames"] = 24, ["frameWidth"] = 56, ["frameHeight"] = 56, ["imageWidth"] = 56, ["imageHeight"] = 1344, ["framerate"] = 25},
	["Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_vargfrost\\lizzievlick.tga"] = {["nFrames"] = 38, ["frameWidth"] = 56, ["frameHeight"] = 56, ["imageWidth"] = 56, ["imageHeight"] = 2128, ["framerate"] = 25},
	["Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_vargfrost\\lizzievnou.tga"] = {["nFrames"] = 10, ["frameWidth"] = 56, ["frameHeight"] = 56, ["imageWidth"] = 56, ["imageHeight"] = 560, ["framerate"] = 12},
	["Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_vargfrost\\lizzievsmush.tga"] = {["nFrames"] = 44, ["frameWidth"] = 56, ["frameHeight"] = 56, ["imageWidth"] = 56, ["imageHeight"] = 2464, ["framerate"] = 25},
	["Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_vargfrost\\lizzievuwu.tga"] = {["nFrames"] = 30, ["frameWidth"] = 56, ["frameHeight"] = 56, ["imageWidth"] = 56, ["imageHeight"] = 1680, ["framerate"] = 25},
	["Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_vargfrost\\lizzievwiggle.tga"] = {["nFrames"] = 48, ["frameWidth"] = 56, ["frameHeight"] = 56, ["imageWidth"] = 56, ["imageHeight"] = 2688, ["framerate"] = 25},
	["Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_vargfrost\\lizzievclappi.tga"] = {["nFrames"] = 29, ["frameWidth"] = 224, ["frameHeight"] = 128, ["imageWidth"] = 224, ["imageHeight"] = 3712, ["framerate"] = 25},
	["Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_vargfrost\\lizzievgigl.tga"] = {["nFrames"] = 10, ["frameWidth"] = 140, ["frameHeight"] = 128, ["imageWidth"] = 140, ["imageHeight"] = 1280, ["framerate"] = 25},
	["Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_vargfrost\\lizzievsmh.tga"] = {["nFrames"] = 9, ["frameWidth"] = 152, ["frameHeight"] = 128, ["imageWidth"] = 152, ["imageHeight"] = 1152, ["framerate"] = 25},
}

TwitchEmotes_emoticons = {
	-- lizzie_vargfrost
	[":33"] = ":33",
	[":333"] = ":333",
	["AAAA"] = "AAAA",
	["AHHH"] = "AHHH",
	["Angy"] = "Angy",
	["bestaSmile"] = "bestaSmile",
	["ICANT"] = "ICANT",
	["KEKW"] = "KEKW",
	["kok"] = "kok",
	["lizzievANGY"] = "lizzievANGY",
	["lizzievARRIVE"] = "lizzievARRIVE",
	["lizzievBLANKIES"] = "lizzievBLANKIES",
	["lizzievBLUSH"] = "lizzievBLUSH",
	["lizzievBONGO"] = "lizzievBONGO",
	["lizzievBUBBLEGUM"] = "lizzievBUBBLEGUM",
	["lizzievCHEER"] = "lizzievCHEER",
	["lizzievCHEERS"] = "lizzievCHEERS",
	["lizzievCHUG"] = "lizzievCHUG",
	["lizzievCLAP"] = "lizzievCLAP",
	["clappi"] = "clappi",
	["lizzievCLEAN"] = "lizzievCLEAN",
	["lizzievCOFFEE"] = "lizzievCOFFEE",
	["lizzievCOPIUM"] = "lizzievCOPIUM",
	["lizzievCOZY"] = "lizzievCOZY",
	["lizzievCULT"] = "lizzievCULT",
	["lizzievDETECTIVE"] = "lizzievDETECTIVE",
	["lizzievDINKDONK"] = "lizzievDINKDONK",
	["lizzievFIGHT"] = "lizzievFIGHT",
	["lizzievFINE"] = "lizzievFINE",
	["lizzievFLEX"] = "lizzievFLEX",
	["lizzievFLOWER"] = "lizzievFLOWER",
	["lizzievFY"] = "lizzievFY",
	["lizzievGIGGLE"] = "lizzievGIGGLE",
	["gigl"] = "gigl",
	["lizzievGUN"] = "lizzievGUN",
	["lizzievHEADBANG"] = "lizzievHEADBANG",
	["lizzievHEARTEYES"] = "lizzievHEARTEYES",
	["lizzievHI"] = "lizzievHI",
	["lizzievHIDE"] = "lizzievHIDE",
	["lizzievHOWDY"] = "lizzievHOWDY",
	["lizzievHUG"] = "lizzievHUG",
	["lizzievKISS"] = "lizzievKISS",
	["lizzievL"] = "lizzievL",
	["lizzievLATE"] = "lizzievLATE",
	["lizzievLEGS"] = "lizzievLEGS",
	["lizzievLICK"] = "lizzievLICK",
	["lizzievLOVE"] = "lizzievLOVE",
	["Madge"] = "Madge",
	["lizzievMONKA"] = "MONKA",
	["lizzievNOU"] = "lizzievNOU",
	["lizzievSAD"] = "lizzievSAD",
	["Sadge"] = "Sadge",
	["lizzievSHY"] = "lizzievSHY",
	["lizzievSIP"] = "lizzievSIP",
	["lizzievSLAY"] = "lizzievSLAY",
	["SMH"] = "SMH",
	["lizzievSMUSH"] = "lizzievSMUSH",
	["lizzievSTAB"] = "lizzievSTAB",
	["lizzievTOFFLA"] = "lizzievTOFFLA",
	["lizzievUWU"] = "lizzievUWU",
	["lizzievWIGGLE"] = "lizzievWIGGLE",
	["lizzievWOWGI"] = "lizzievWOWGI",
	["lizzievYESSIR"] = "lizzievYESSIR",
	["nolook"] = "nolook",
	["oshit"] = "oshit",
	["SLAYYY"] = "SLAYYY",
	["YAAAS"] = "YAAAS",
};

TwitchEmotes_ExcludedSuggestions = {
	"Jons", ":jons:", ":twoofakind:", "HammersArk", "HammersNoArk", "Shelia", "LULWWW", ":mo:", ":penguin:", "Gerdlerk1", "Gerdlerk2", "Gerdlerk3", "Gerdlerk4", "Lucimage", "Bowtherapy", "NickyQW","gachiSLAPW","peepoMadW","FeelsBadManW","FeelsGoodManW","FeelsgoodManW","FeelsOkayManW","FeelsSleepyManW","PepeHandsW","PepeJAMW","WeirdWW","MooCowW","peepoLoveW","peepoPlotW","FeelsCryManW","monakW","LovepeepoW","WeirdJAMW","peepoExitW","FeelsLoveManW","HeartatoW","KEKWW","PogWartsW",":epicW:","Lyeasy","LyeREE","LyeCute","LyEZ","LyeShrug",":smook:","SmookDead","SmookEvil","SmookGasm","SmookMad","SmookNervous","SmookSad","SmookSpook","SmookWeird","SmookWink","SmookSmile", "unholysip", "BedgeMorgan", "MikeSmug"
}
