TwitchEmotes_defaultpack = {
	-- lizzie_vargfrost
	["lizzievangy"] = "Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_vargfrost\\lizzievangy.tga:28:28",
	["lizzievarrive"] = "Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_vargfrost\\lizzievarrive.tga:28:28",
	["lizzievblankies"] = "Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_vargfrost\\lizzievblankies.tga:28:28",
	["lizzievblush"] = "Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_vargfrost\\lizzievblush.tga:28:28",
	["lizzievbongo"] = "Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_vargfrost\\lizzievbongo.tga:28:28",
	["lizzievbubblegum"] = "Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_vargfrost\\lizzievbubblegum.tga:28:28",
	[":33"] = "Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_vargfrost\\lizzievcat.tga:28:28",
	["lizzievcheer"] = "Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_vargfrost\\lizzievcheer.tga:28:28",
	["lizzievcheers"] = "Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_vargfrost\\lizzievcheers.tga:28:28",
	["lizzievchug"] = "Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_vargfrost\\lizzievchug.tga:28:28",
	["lizzievclap"] = "Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_vargfrost\\lizzievclap.tga:28:28",
	["lizzievclean"] = "Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_vargfrost\\lizzievclean.tga:28:28",
	["lizzievcoffee"] = "Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_vargfrost\\lizzievcoffee.tga:28:28",
	["lizzievcopium"] = "Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_vargfrost\\lizzievcopium.tga:28:28",
	["lizzievcozy"] = "Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_vargfrost\\lizzievcozy.tga:28:28",
	["lizzievcult"] = "Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_vargfrost\\lizzievcult.tga:28:28",
	["lizzievdetective"] = "Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_vargfrost\\lizzievdetective.tga:28:28",
	["lizzievdinkdonk"] = "Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_vargfrost\\lizzievdinkdonk.tga:28:28",
	["lizzievfight"] = "Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_vargfrost\\lizzievfight.tga:28:28",
	["lizzievfine"] = "Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_vargfrost\\lizzievfine.tga:28:28",
	["lizzievflex"] = "Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_vargfrost\\lizzievflex.tga:28:28",
	["lizzievflower"] = "Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_vargfrost\\lizzievflower.tga:28:28",
	["lizzievfy"] = "Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_vargfrost\\lizzievfy.tga:28:28",
	["lizzievgiggle"] = "Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_vargfrost\\lizzievgiggle.tga:28:28",
	["lizzievgun"] = "Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_vargfrost\\lizzievgun.tga:28:28",
	["lizzievheadbang"] = "Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_vargfrost\\lizzievheadbang.tga:28:28",
	["lizzievhearteyes"] = "Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_vargfrost\\lizzievhearteyes.tga:28:28",
	["lizzievhi"] = "Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_vargfrost\\lizzievhi.tga:28:28",
	["lizzievhide"] = "Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_vargfrost\\lizzievhide.tga:28:28",
	["lizzievhowdy"] = "Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_vargfrost\\lizzievhowdy.tga:28:28",
	["lizzievhug"] = "Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_vargfrost\\lizzievhug.tga:28:28",
	["lizzievkiss"] = "Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_vargfrost\\lizzievkiss.tga:28:28",
	["lizzievl"] = "Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_vargfrost\\lizzievl.tga:28:28",
	["lizzievlate"] = "Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_vargfrost\\lizzievlate.tga:28:28",
	["lizzievlegs"] = "Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_vargfrost\\lizzievlegs.tga:28:28",
	["lizzievlick"] = "Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_vargfrost\\lizzievlick.tga:28:28",
	["lizzievlove"] = "Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_vargfrost\\lizzievlove.tga:28:28",
	["lizzievnou"] = "Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_vargfrost\\lizzievnou.tga:28:28",
	["lizzievsad"] = "Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_vargfrost\\lizzievsad.tga:28:28",
	["lizzievshy"] = "Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_vargfrost\\lizzievshy.tga:28:28",
	["lizzievsip"] = "Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_vargfrost\\lizzievsip.tga:28:28",
	["lizzievslay"] = "Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_vargfrost\\lizzievslay.tga:28:28",
	["lizzievsmush"] = "Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_vargfrost\\lizzievsmush.tga:28:28",
	["lizzievstab"] = "Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_vargfrost\\lizzievstab.tga:28:28",
	["lizzievtoffla"] = "Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_vargfrost\\lizzievtoffla.tga:28:28",
	["lizzievuwu"] = "Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_vargfrost\\lizzievuwu.tga:28:28",
	["lizzievwiggle"] = "Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_vargfrost\\lizzievwiggle.tga:28:28",
	["lizzievwowgi"] = "Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_vargfrost\\lizzievwowgi.tga:28:28",
	["lizzievyessir"] = "Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_vargfrost\\lizzievyessir.tga:28:28",
};

TwitchEmotes_animation_metadata = {
	["Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_vargfrost\\lizzievangy.tga"] = {["nFrames"] = 53, ["frameWidth"] = 56, ["frameHeight"] = 56, ["imageWidth"] = 56, ["imageHeight"] = 2968, ["framerate"] = 25},
	["Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_vargfrost\\lizzievarrive.tga"] = {["nFrames"] = 60, ["frameWidth"] = 56, ["frameHeight"] = 56, ["imageWidth"] = 56, ["imageHeight"] = 3360, ["framerate"] = 25},
	["Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_vargfrost\\lizzievblankies.tga"] = {["nFrames"] = 24, ["frameWidth"] = 56, ["frameHeight"] = 56, ["imageWidth"] = 56, ["imageHeight"] = 1344, ["framerate"] = 25},
	["Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_vargfrost\\lizzievbongo.tga"] = {["nFrames"] = 12, ["frameWidth"] = 56, ["frameHeight"] = 56, ["imageWidth"] = 56, ["imageHeight"] = 672, ["framerate"] = 25},
	["Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_vargfrost\\lizzievbubblegum.tga"] = {["nFrames"] = 60, ["frameWidth"] = 56, ["frameHeight"] = 56, ["imageWidth"] = 56, ["imageHeight"] = 3360, ["framerate"] = 25},
	["Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_vargfrost\\lizzievcheer.tga"] = {["nFrames"] = 38, ["frameWidth"] = 56, ["frameHeight"] = 56, ["imageWidth"] = 56, ["imageHeight"] = 2128, ["framerate"] = 25},
	["Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_vargfrost\\lizzievcheers.tga"] = {["nFrames"] = 27, ["frameWidth"] = 56, ["frameHeight"] = 56, ["imageWidth"] = 56, ["imageHeight"] = 1512, ["framerate"] = 25},
	["Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_vargfrost\\lizzievchug.tga"] = {["nFrames"] = 16, ["frameWidth"] = 56, ["frameHeight"] = 56, ["imageWidth"] = 56, ["imageHeight"] = 896, ["framerate"] = 25},
	["Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_vargfrost\\lizzievclap.tga"] = {["nFrames"] = 10, ["frameWidth"] = 56, ["frameHeight"] = 56, ["imageWidth"] = 56, ["imageHeight"] = 560, ["framerate"] = 25},
	["Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_vargfrost\\lizzievclean.tga"] = {["nFrames"] = 24, ["frameWidth"] = 56, ["frameHeight"] = 56, ["imageWidth"] = 56, ["imageHeight"] = 1344, ["framerate"] = 25},
	["Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_vargfrost\\lizzievcoffee.tga"] = {["nFrames"] = 40, ["frameWidth"] = 56, ["frameHeight"] = 56, ["imageWidth"] = 56, ["imageHeight"] = 2240, ["framerate"] = 25},
	["Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_vargfrost\\lizzievdinkdonk.tga"] = {["nFrames"] = 8, ["frameWidth"] = 56, ["frameHeight"] = 56, ["imageWidth"] = 56, ["imageHeight"] = 448, ["framerate"] = 25},
	["Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_vargfrost\\lizzievflower.tga"] = {["nFrames"] = 41, ["frameWidth"] = 56, ["frameHeight"] = 56, ["imageWidth"] = 56, ["imageHeight"] = 2296, ["framerate"] = 25},
	["Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_vargfrost\\lizzievheadbang.tga"] = {["nFrames"] = 6, ["frameWidth"] = 56, ["frameHeight"] = 56, ["imageWidth"] = 56, ["imageHeight"] = 336, ["framerate"] = 25},
	["Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_vargfrost\\lizzievhi.tga"] = {["nFrames"] = 24, ["frameWidth"] = 56, ["frameHeight"] = 56, ["imageWidth"] = 56, ["imageHeight"] = 1344, ["framerate"] = 25},
	["Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_vargfrost\\lizzievhide.tga"] = {["nFrames"] = 28, ["frameWidth"] = 56, ["frameHeight"] = 56, ["imageWidth"] = 56, ["imageHeight"] = 1568, ["framerate"] = 25},
	["Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_vargfrost\\lizzievhowdy.tga"] = {["nFrames"] = 29, ["frameWidth"] = 56, ["frameHeight"] = 56, ["imageWidth"] = 56, ["imageHeight"] = 1624, ["framerate"] = 25},
	["Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_vargfrost\\lizzievkiss.tga"] = {["nFrames"] = 27, ["frameWidth"] = 56, ["frameHeight"] = 56, ["imageWidth"] = 56, ["imageHeight"] = 1512, ["framerate"] = 25},
	["Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_vargfrost\\lizzievl.tga"] = {["nFrames"] = 48, ["frameWidth"] = 56, ["frameHeight"] = 56, ["imageWidth"] = 56, ["imageHeight"] = 2688, ["framerate"] = 25},
	["Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_vargfrost\\lizzievlegs.tga"] = {["nFrames"] = 24, ["frameWidth"] = 56, ["frameHeight"] = 56, ["imageWidth"] = 56, ["imageHeight"] = 1344, ["framerate"] = 25},
	["Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_vargfrost\\lizzievlick.tga"] = {["nFrames"] = 38, ["frameWidth"] = 56, ["frameHeight"] = 56, ["imageWidth"] = 56, ["imageHeight"] = 2128, ["framerate"] = 25},
	["Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_vargfrost\\lizzievnou.tga"] = {["nFrames"] = 10, ["frameWidth"] = 56, ["frameHeight"] = 56, ["imageWidth"] = 56, ["imageHeight"] = 560, ["framerate"] = 25},
	["Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_vargfrost\\lizzievsmush.tga"] = {["nFrames"] = 44, ["frameWidth"] = 56, ["frameHeight"] = 56, ["imageWidth"] = 56, ["imageHeight"] = 2464, ["framerate"] = 25},
	["Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_vargfrost\\lizzievuwu.tga"] = {["nFrames"] = 30, ["frameWidth"] = 56, ["frameHeight"] = 56, ["imageWidth"] = 56, ["imageHeight"] = 1680, ["framerate"] = 25},
	["Interface\\AddOns\\LizzieEmotes\\Emotes\\lizzie_vargfrost\\lizzievwiggle.tga"] = {["nFrames"] = 48, ["frameWidth"] = 56, ["frameHeight"] = 56, ["imageWidth"] = 56, ["imageHeight"] = 2688, ["framerate"] = 25},
}

TwitchEmotes_emoticons = {
	-- lizzie_vargfrost
	["lizzievangy"] = "lizzievangy",
	["lizzievarrive"] = "lizzievarrive",
	["lizzievblankies"] = "lizzievblankies",
	["lizzievblush"] = "lizzievblush",
	["lizzievbongo"] = "lizzievbongo",
	["lizzievbubblegum"] = "lizzievbubblegum",
	[":33"] = ":33",
	["lizzievcheer"] = "lizzievcheer",
	["lizzievcheers"] = "lizzievcheers",
	["lizzievchug"] = "lizzievchug",
	["lizzievclap"] = "lizzievclap",
	["lizzievclean"] = "lizzievclean",
	["lizzievcoffee"] = "lizzievcoffee",
	["lizzievcopium"] = "lizzievcopium",
	["lizzievcozy"] = "lizzievcozy",
	["lizzievcult"] = "lizzievcult",
	["lizzievdetective"] = "lizzievdetective",
	["lizzievdinkdonk"] = "lizzievdinkdonk",
	["lizzievfight"] = "lizzievfight",
	["lizzievfine"] = "lizzievfine",
	["lizzievflex"] = "lizzievflex",
	["lizzievflower"] = "lizzievflower",
	["lizzievfy"] = "lizzievfy",
	["lizzievgiggle"] = "lizzievgiggle",
	["lizzievgun"] = "lizzievgun",
	["lizzievheadbang"] = "lizzievheadbang",
	["lizzievhearteyes"] = "lizzievhearteyes",
	["lizzievhi"] = "lizzievhi",
	["lizzievhide"] = "lizzievhide",
	["lizzievhowdy"] = "lizzievhowdy",
	["lizzievhug"] = "lizzievhug",
	["lizzievkiss"] = "lizzievkiss",
	["lizzievl"] = "lizzievl",
	["lizzievlate"] = "lizzievlate",
	["lizzievlegs"] = "lizzievlegs",
	["lizzievlick"] = "lizzievlick",
	["lizzievlove"] = "lizzievlove",
	["lizzievnou"] = "lizzievnou",
	["lizzievsad"] = "lizzievsad",
	["lizzievshy"] = "lizzievshy",
	["lizzievsip"] = "lizzievsip",
	["lizzievslay"] = "lizzievslay",
	["lizzievsmush"] = "lizzievsmush",
	["lizzievstab"] = "lizzievstab",
	["lizzievtoffla"] = "lizzievtoffla",
	["lizzievuwu"] = "lizzievuwu",
	["lizzievwiggle"] = "lizzievwiggle",
	["lizzievwowgi"] = "lizzievwowgi",
	["lizzievyessir"] = "lizzievyessir",
};

TwitchEmotes_ExcludedSuggestions = {
	"Jons", ":jons:", ":twoofakind:", "HammersArk", "HammersNoArk", "Shelia", "LULWWW", ":mo:", ":penguin:", "Gerdlerk1", "Gerdlerk2", "Gerdlerk3", "Gerdlerk4", "Lucimage", "Bowtherapy", "NickyQW","gachiSLAPW","peepoMadW","FeelsBadManW","FeelsGoodManW","FeelsgoodManW","FeelsOkayManW","FeelsSleepyManW","PepeHandsW","PepeJAMW","WeirdWW","MooCowW","peepoLoveW","peepoPlotW","FeelsCryManW","monakW","LovepeepoW","WeirdJAMW","peepoExitW","FeelsLoveManW","HeartatoW","KEKWW","PogWartsW",":epicW:","Lyeasy","LyeREE","LyeCute","LyEZ","LyeShrug",":smook:","SmookDead","SmookEvil","SmookGasm","SmookMad","SmookNervous","SmookSad","SmookSpook","SmookWeird","SmookWink","SmookSmile", "unholysip", "BedgeMorgan", "MikeSmug"
}
